Extension { #name : #WATagBrush }

{ #category : #'*FomanticUI-Core' }
WATagBrush >> active [                   

	self class: 'active'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> animated [   

	self class: 'animated'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> basic [   

	self class: 'basic'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> black [                  

	self class: 'black'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> blue [            

	self class: 'blue'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> brown [                

	self class: 'brown'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> button [   

	self class: 'button'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> buttons [                   

	self class: 'buttons'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> column [  

	self class: 'column'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> green [          

	self class: 'green'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> grey [                 

	self class: 'grey'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> grid [     

	self class: 'grid'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> icon [   

	self class: 'icon'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> inverted [                   

	self class: 'inverted'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> labeled [   

	self class: 'labeled'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> negative [      

	self class: 'negative'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> olive [         

	self class: 'olive'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> or [                   

	self class: 'or'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> orange [        

	self class: 'orange'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> pink [               

	self class: 'pink'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> placeholder [ 

	self class: 'placeholder'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> positive [                   

	self class: 'positive'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> primary [   

	self class: 'primary'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> purple [              

	self class: 'purple'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> red [       

	self class: 'red'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> relaxed [    

	self class: 'relaxed'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> secondary [    

	self class: 'secondary'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> segment [ 

	self class: 'segment'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> stackable [     

	self class: 'stackable'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> teal [           

	self class: 'teal'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> tertiary [                  

	self class: 'tertiary'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> two [  

	self class: 'two'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> ui [

	self class: 'ui'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> very [   

	self class: 'very'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> violet [             

	self class: 'violet'
]

{ #category : #'*FomanticUI-Core' }
WATagBrush >> yellow [        

	self class: 'yellow'
]
